//! Deferred linting and formatting for coding agents.
//!
//! The initial `scaffold` module was generated by Copier and now provides the
//! unified CLI around Velvet Glove's migrated immediate and deferred runners.

pub mod hooks;
pub mod scaffold;

/// Dispatch one parsed CLI invocation through its exact HookKit contract.
pub fn run(cli: scaffold::cli::Cli) -> std::process::ExitCode {
    scaffold::dispatch::run(cli)
}
