//! @generated by `cargo xtask template-catalog sync`; customize after copying.
//! Portable `post_tool` handler.

#[rustfmt::skip]
pub fn handle(
    _input: hookkit_common::PostToolUseInput,
    _environment: &hookkit_common::PostToolUseCommandEnvironment,
    context: &hookkit_core::RuntimeContext<'_>,
    _state_dir: Option<&std::path::Path>,
) -> hookkit_core::Result<hookkit_common::PostToolUseOutput> {
    hookkit_common::PostToolUseOutput::no_op(context.harness())
}
