//! @generated by `cargo xtask template-catalog sync`; customize after copying.
//! Portable `turn_completion` handler.

#[rustfmt::skip]
pub fn handle(
    _input: hookkit_common::TurnCompletionInput,
    _environment: &hookkit_common::TurnCompletionCommandEnvironment,
    context: &hookkit_core::RuntimeContext<'_>,
    _state_dir: Option<&std::path::Path>,
) -> hookkit_core::Result<hookkit_common::TurnCompletionOutput> {
    hookkit_common::TurnCompletionOutput::allow(context.harness())
}
